### ISSUE TITLE
The useage of config files

### ISSUE THREAD

**Issue by zbf1991** [bcmi/SimFormer-Weak-Shot-Semantic-Segmentation#1]
Many thanks for your excellent work, I found there are many config files. For example, s1_seg.yaml, s1_seg_crosim.yaml, s1_seg_pseudo_label.yaml and s1_seg_retraining.yaml for ADE20K split1. Could you please explain the usage of above different .yaml files?

**Comment by zbf1991** [comment]
Also, When I direct run the code by changing s1_seg.yaml to s1_seg_crosim.yaml, it report "Not Found: datasets/imname_to_pair_list_dict_ADE_split1_train.pth".

**Comment by chenbys** [comment]
Thanks for the comments. Different cfgs are used for different sets of hyper-parameters, as described in 4.4 Training. The pre-statistics of module is under the corresponding folder, as prop_former/modeling/cross_img_sim/compute_pairs.py.

**Comment by zbf1991** [comment]
Thanks for your reply, I have successfully used prop_former/modeling/cross_img_sim/compute_pairs.py, to produce imname_to_pair_list_dict_ADE_split1_train.pth. But when I continue to run the code using s1_seg_crosim.yaml as config file, it reports assert B == 2, f'only support BS=2 for shuffle yet'. Could you please tell me how I can make it work?
