### ISSUE TITLE
The 'imname_to_pair_list_dict_ADE_split1_train.pth' file is not found?

### ISSUE THREAD

**Issue by yhg1010** [bcmi/SimFormer-Weak-Shot-Semantic-Segmentation#2]
<img width="1440" alt="截屏2023-03-14 13 25 14" src="https://user-images.githubusercontent.com/61537981/224904473-d9889a50-264a-4eb3-82fe-1e002125af65.png">
when i run the script using the config file 'SimFormer-Weak-Shot-Semantic-Segmentation-main/_1Prop_Cfgs/ade20k-150/s1_seg_crosim.yaml', it shows that the pth file is not found. thanks for a replay.

**Comment by chenbys** [comment]
Thanks for attention. The generating scripts are under module folders, e.g.:

https://github.com/bcmi/SimFormer-Weak-Shot-Semantic-Segmentation/blob/main/prop_former/modeling/cross_img_sim/compute_pairs.py

**Comment by yhg1010** [comment]
Thanks for a replay!
