### ISSUE TITLE
  Request visual code

### ISSUE THREAD

**Issue by ClearShadow7** [bcmi/SimFormer-Weak-Shot-Semantic-Segmentation#3]
Hello! I am learning your article and code, but I can't find the visualization code in the process of learning. Can you provide the relevant code of the visualization part in your article, or the preference code of a single image that can be visualized, or the visualization code that can be referenced, so that I can further study, thank you!

**Comment by chenbys** [comment]
Thanks for your interest in this work.
I have uploaded a [viz script]( https://github.com/bcmi/SimFormer-Weak-Shot-Semantic-Segmentation/blob/main/figs/viz_func.py ) for references, and the usages could be easily inferred according to the variable names.

**Comment by ClearShadow7** [comment]
Thank you for your code！I will study it carefully.

**Comment by ClearShadow7** [comment]
Hello! After learning your code, I still have some issues that I don't understand. I would like to request a comparative study of the specific sample code that you implemented visualization. I wonder if it would be convenient for you to provide the following code? thank you!
